name: HEAVY Release Builder
on:
  workflow_dispatch: {}
  push:
    tags: ['v*']

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Base APT packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates curl wget unzip tar git build-essential pkg-config \
            libssl-dev ruby-full nmap sqlmap ffuf gobuster \
            tshark exiftool default-jre python3-venv

      # --- TRIVY (Aqua repo) ---
      - name: Install Trivy (Aqua Security)
        run: |
          sudo apt-get install -y --no-install-recommends gnupg software-properties-common
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # --- Go-based tools ---
      - name: Install Go-based tools
        run: |
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          go install github.com/tomnomnom/waybackurls@latest
          go install github.com/jaeles-project/uro/cmd/uro@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest

      # --- Gems / PyPI tools ---
      - name: Install WPScan, zsteg, volatility3, wafw00f
        run: |
          # Ruby gems
          sudo gem install wpscan
          sudo gem install zsteg
          # Python tools (user install places into ~/.local/bin)
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user volatility3 wafw00f

      # --- nuclei templates ---
      - name: Update nuclei templates
        run: |
          export PATH=$HOME/go/bin:$PATH
          nuclei -update-templates || true
          echo "templates at $HOME/.local/share/nuclei-templates"

      # --- Vendor heavy assets into ./vendor ---
      - name: Vendor heavy assets
        run: |
          set -e
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
          mkdir -p vendor/bin vendor/seclists vendor/nuclei-templates

          # Go binaries
          cp -a $HOME/go/bin/* vendor/bin/ || true

          # System binaries
          for b in /usr/bin/sqlmap /usr/bin/ffuf /usr/bin/gobuster /usr/bin/trivy /usr/bin/tshark /usr/bin/nmap; do
            if [ -x "$b" ]; then cp "$b" vendor/bin/; fi
          done

          # WPScan shim (gem executable)
          if command -v wpscan >/dev/null 2>&1; then
            mkdir -p vendor/bin
            ln -sf "$(command -v wpscan)" vendor/bin/wpscan
          fi

          # zsteg (gem executable)
          if command -v zsteg >/dev/null 2>&1; then
            ln -sf "$(command -v zsteg)" vendor/bin/zsteg
          fi

          # wafw00f (pip user)
          if command -v wafw00f >/dev/null 2>&1; then
            ln -sf "$(command -v wafw00f)" vendor/bin/wafw00f
          else
            if [ -x "$HOME/.local/bin/wafw00f" ]; then ln -sf "$HOME/.local/bin/wafw00f" vendor/bin/wafw00f; fi
          fi

          # volatility3 (pip user)
          if command -v volatility3 >/dev/null 2>&1; then
            ln -sf "$(command -v volatility3)" vendor/bin/volatility3
          else
            if [ -x "$HOME/.local/bin/volatility3" ]; then ln -sf "$HOME/.local/bin/volatility3" vendor/bin/volatility3; fi
          fi

          # SecLists (vendor via git clone since no apt pkg)
          git clone --depth=1 https://github.com/danielmiessler/SecLists.git vendor/seclists

          # nuclei templates
          if [ -d $HOME/.local/share/nuclei-templates ]; then
            cp -a $HOME/.local/share/nuclei-templates vendor/nuclei-templates
          fi

      # --- Compose heavy ZIP ---
      - name: Compose heavy ZIP
        run: |
          NAME="3rd_EAI_HEAVY_FULL_$(date +%Y%m%d_%H%M%S).zip"
          zip -r "$NAME" . -x ".git/*" -x "vendor/*.zip"
          echo "ZIP_NAME=$NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}

      - name: Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
